/*
 * GENERATED — do not edit by hand. Run: npx tsx scripts/generate-theme-v3.ts
 * Source: themes/themes.ts (THEME_FAMILIES_DATA).
 *
 * Named ThemeFamily objects (the same palettes as themes.css). Pass one as
 * `<Calendar theme={dracula} />` to tree-shake a single theme, or use the
 * string form `theme="dracula"` to ride the generated stylesheet instead.
 */
import { THEME_BRAND, type ThemeFamily } from "./theme-tokens";

export const abyss: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#d400f0",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#d400f022",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#ff6b35",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#d400f0",
      "--c-activeText": "#060009",
      "--c-backdrop": "#060009",
      "--c-tone": "#1c0030",
      "--c-text": "#f0d0ff",
      "--c-stroke": "#2e0050",
      "--c-shadow": "#d400f028",
      "--c-disabled": "#2a0040",
      "--c-mutedText": "#8a7594",
      "--c-disabledText": "#917b9b",
      "--c-weekend": "#00ffee",
      "--c-range": "#ff6b35",
      "--c-error": "#ff1744",
      "--c-outOfMonth": "#917b9b",
      "--c-focusRing": "#09010e",
    },
  },
};
export const aurora: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#3de0a0",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#3de0a022",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#00d4f5",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#3de0a0",
      "--c-activeText": "#07091a",
      "--c-backdrop": "#0b0e24",
      "--c-tone": "#131838",
      "--c-text": "#e0f9f0",
      "--c-stroke": "#2a1f5a",
      "--c-shadow": "#3de0a028",
      "--c-disabled": "#2d3560",
      "--c-mutedText": "#79878d",
      "--c-disabledText": "#7e8d92",
      "--c-weekend": "#ff5fa2",
      "--c-range": "#00d4f5",
      "--c-error": "#ff5252",
      "--c-outOfMonth": "#7e8d92",
      "--c-focusRing": "#07091a",
    },
  },
};
export const bauhaus: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#1a1c2a",
      "--c-activeText": "#ede2c2",
      "--c-backdrop": "#ede2c2",
      "--c-tone": "#e2d4ad",
      "--c-text": "#1a1c2a",
      "--c-stroke": "#b29766",
      "--c-shadow": "#1a1c2a1c",
      "--c-disabled": "#c6b687",
      "--c-mutedText": "#4d4530",
      "--c-disabledText": "#5a4f30",
      "--c-weekend": "#971c14",
      "--c-range": "#d4a84a",
      "--c-error": "#9a1f17",
      "--c-outOfMonth": "#5a4f30",
      "--c-focusRing": "#1a1c2a",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#d8d1b8",
      "--c-activeText": "#161420",
      "--c-backdrop": "#161420",
      "--c-tone": "#21202e",
      "--c-text": "#d8d1b8",
      "--c-stroke": "#363448",
      "--c-shadow": "#1614202a",
      "--c-disabled": "#2e2d3c",
      "--c-mutedText": "#9a98a8",
      "--c-disabledText": "#8a8898",
      "--c-weekend": "#ef6e58",
      "--c-range": "#5a7090",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#8a8898",
      "--c-focusRing": "#d8d1b8",
    },
  },
};
export const chalk: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#2a2e5c",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#f0f0f3",
      "--c-tone": "#e2e2e8",
      "--c-text": "#0e1028",
      "--c-stroke": "#cbcbd4",
      "--c-shadow": "#2a2e5c22",
      "--c-disabled": "#999cab",
      "--c-mutedText": "#616272",
      "--c-disabledText": "#5b5d6d",
      "--c-weekend": "#a92847",
      "--c-range": "#5866a8",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#5b5d6d",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#2a2e5c",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#0b1014",
      "--c-tone": "#151c22",
      "--c-text": "#eef4f2",
      "--c-stroke": "#26333a",
      "--c-shadow": "#2a2e5c28",
      "--c-disabled": "#334047",
      "--c-mutedText": "#91a19f",
      "--c-disabledText": "#98a8a6",
      "--c-weekend": "#ff7a7a",
      "--c-range": "#5866a8",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#98a8a6",
      "--c-focusRing": "#ffffff",
    },
  },
};
export const crimson: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#d92121",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#fff5f5",
      "--c-tone": "#ffe4e4",
      "--c-text": "#1c0808",
      "--c-stroke": "#f4b4b4",
      "--c-shadow": "#d9212124",
      "--c-disabled": "#c89898",
      "--c-mutedText": "#746464",
      "--c-disabledText": "#6f5f5f",
      "--c-weekend": "#b91c1c",
      "--c-range": "#ff9800",
      "--c-error": "#7f1d1d",
      "--c-outOfMonth": "#6f5f5f",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#f92f2f",
      "--c-activeText": "#0d0909",
      "--c-backdrop": "#0d0909",
      "--c-tone": "#3a1616",
      "--c-text": "#ffffff",
      "--c-stroke": "#2b1a1a",
      "--c-shadow": "#f92f2f2c",
      "--c-disabled": "#5a3535",
      "--c-mutedText": "#8b8989",
      "--c-disabledText": "#929090",
      "--c-weekend": "#ff6b6b",
      "--c-range": "#ff9800",
      "--c-error": "#fbbf24",
      "--c-outOfMonth": "#929090",
      "--c-focusRing": "#161111",
    },
  },
};
export const cyber: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#00f3ff",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#00f3ff22",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#ff6d00",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#00f3ff",
      "--c-activeText": "#07070b",
      "--c-backdrop": "#07070b",
      "--c-tone": "#301649",
      "--c-text": "#ffffff",
      "--c-stroke": "#303050",
      "--c-shadow": "#00f3ff2c",
      "--c-disabled": "#282840",
      "--c-mutedText": "#8c8c8d",
      "--c-disabledText": "#929294",
      "--c-weekend": "#e040fb",
      "--c-range": "#ff6d00",
      "--c-error": "#ff1744",
      "--c-outOfMonth": "#929294",
      "--c-focusRing": "#0d0d15",
    },
  },
};
export const dracula: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#ff5e5e",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#ff5e5e22",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#ffd740",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#ff5e5e",
      "--c-activeText": "#111111",
      "--c-backdrop": "#1c1111",
      "--c-tone": "#341d1d",
      "--c-text": "#ffffff",
      "--c-stroke": "#614040",
      "--c-shadow": "#ff5e5e2c",
      "--c-disabled": "#583535",
      "--c-mutedText": "#908b8b",
      "--c-disabledText": "#969191",
      "--c-weekend": "#ff6b6b",
      "--c-range": "#ffd740",
      "--c-error": "#fbbf24",
      "--c-outOfMonth": "#969191",
      "--c-focusRing": "#1a0f0f",
    },
  },
};
export const eclipse: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#b7e000",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#b7e00022",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#a78bfa",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#b7e000",
      "--c-activeText": "#080d09",
      "--c-backdrop": "#080d09",
      "--c-tone": "#141a12",
      "--c-text": "#e9f2c7",
      "--c-stroke": "#304024",
      "--c-shadow": "#b7e00024",
      "--c-disabled": "#3b442e",
      "--c-mutedText": "#7f866d",
      "--c-disabledText": "#858c72",
      "--c-weekend": "#ff5d8f",
      "--c-range": "#a78bfa",
      "--c-error": "#ff3d68",
      "--c-outOfMonth": "#858c72",
      "--c-focusRing": "#f4ffd8",
    },
  },
};
export const espresso: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#6f3d18",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#faf8f4",
      "--c-tone": "#f2eddf",
      "--c-text": "#1a1208",
      "--c-stroke": "#d8c8a8",
      "--c-shadow": "#6f3d1826",
      "--c-disabled": "#9e8f78",
      "--c-mutedText": "#6f6961",
      "--c-disabledText": "#69635b",
      "--c-weekend": "#7c3f12",
      "--c-range": "#4a90d9",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#69635b",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#a05878",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#0c0608",
      "--c-tone": "#1e0e14",
      "--c-text": "#e8c8d4",
      "--c-stroke": "#341424",
      "--c-shadow": "#a0587828",
      "--c-disabled": "#2e1020",
      "--c-mutedText": "#8f7981",
      "--c-disabledText": "#967f88",
      "--c-weekend": "#c07028",
      "--c-range": "#4a90d9",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#967f88",
      "--c-focusRing": "#f8f0f4",
    },
  },
};
export const fjord: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#14b8a6",
      "--c-activeText": "#062b2f",
      "--c-backdrop": "#f0fdff",
      "--c-tone": "#dff7f8",
      "--c-text": "#082f36",
      "--c-stroke": "#a7e3e6",
      "--c-shadow": "#14b8a620",
      "--c-disabled": "#84bfc4",
      "--c-mutedText": "#4f6f75",
      "--c-disabledText": "#4a686e",
      "--c-weekend": "#b91c1c",
      "--c-range": "#0ea5e9",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#4a686e",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#2fa39b",
      "--c-activeText": "#091113",
      "--c-backdrop": "#0e1416",
      "--c-tone": "#131c1f",
      "--c-text": "#eaf3f2",
      "--c-stroke": "#223136",
      "--c-shadow": "#2fa39b26",
      "--c-disabled": "#5f6e6c",
      "--c-mutedText": "#8ea3a0",
      "--c-disabledText": "#788b88",
      "--c-weekend": "#d56d64",
      "--c-range": "#38b8ae",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#788b88",
      "--c-focusRing": "#eaf3f2",
    },
  },
};
export const graphite: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#f1a01d",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f7f8f9",
      "--c-tone": "#eeeff1",
      "--c-text": "#1a1a1a",
      "--c-stroke": "#e2e4e8",
      "--c-shadow": "#f1a01d1e",
      "--c-disabled": "#9aa0aa",
      "--c-mutedText": "#6a6b6b",
      "--c-disabledText": "#656566",
      "--c-weekend": "#c62828",
      "--c-range": "#4a90d9",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#656566",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#f1a01d",
      "--c-activeText": "#111111",
      "--c-backdrop": "#0b1014",
      "--c-tone": "#151c22",
      "--c-text": "#eef4f2",
      "--c-stroke": "#26333a",
      "--c-shadow": "#f1a01d28",
      "--c-disabled": "#334047",
      "--c-mutedText": "#91a19f",
      "--c-disabledText": "#98a8a6",
      "--c-weekend": "#ff7a7a",
      "--c-range": "#4a90d9",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#98a8a6",
      "--c-focusRing": "#111111",
    },
  },
};
export const industrial: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#e85d00",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#e85d0022",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#f1c40f",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#e85d00",
      "--c-activeText": "#111111",
      "--c-backdrop": "#111111",
      "--c-tone": "#1c1c1c",
      "--c-text": "#d4d4d4",
      "--c-stroke": "#2a2a2a",
      "--c-shadow": "#e85d0030",
      "--c-disabled": "#505050",
      "--c-mutedText": "#868686",
      "--c-disabledText": "#8c8c8c",
      "--c-weekend": "#ff7043",
      "--c-range": "#f1c40f",
      "--c-error": "#ef4444",
      "--c-outOfMonth": "#8c8c8c",
      "--c-focusRing": "#ffffff",
    },
  },
};
export const meadow: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#059669",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f2faf7",
      "--c-tone": "#d1fae5",
      "--c-text": "#052e16",
      "--c-stroke": "#a7f3d0",
      "--c-shadow": "#05966920",
      "--c-disabled": "#6ee7b7",
      "--c-mutedText": "#547261",
      "--c-disabledText": "#4e6d5c",
      "--c-weekend": "#be123c",
      "--c-range": "#0ea5e9",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#4e6d5c",
      "--c-focusRing": "#071a10",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#4ade80",
      "--c-activeText": "#111111",
      "--c-backdrop": "#0f2016",
      "--c-tone": "#162b1e",
      "--c-text": "#e2f5e8",
      "--c-stroke": "#255038",
      "--c-shadow": "#4ade8028",
      "--c-disabled": "#1d3c2a",
      "--c-mutedText": "#819488",
      "--c-disabledText": "#889a8e",
      "--c-weekend": "#86efac",
      "--c-range": "#fb923c",
      "--c-error": "#ef4444",
      "--c-outOfMonth": "#889a8e",
      "--c-focusRing": "#0c1a10",
    },
  },
};
export const mint: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#60d276",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8f9fc",
      "--c-tone": "#eaedf4",
      "--c-text": "#171827",
      "--c-stroke": "#b8c0d1",
      "--c-shadow": "#60d27620",
      "--c-disabled": "#8898aa",
      "--c-mutedText": "#686974",
      "--c-disabledText": "#62636e",
      "--c-weekend": "#c62828",
      "--c-range": "#7c4dff",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#62636e",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#60d276",
      "--c-activeText": "#111111",
      "--c-backdrop": "#0b1014",
      "--c-tone": "#151c22",
      "--c-text": "#eef4f2",
      "--c-stroke": "#26333a",
      "--c-shadow": "#60d27628",
      "--c-disabled": "#334047",
      "--c-mutedText": "#91a19f",
      "--c-disabledText": "#98a8a6",
      "--c-weekend": "#ff7a7a",
      "--c-range": "#7c4dff",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#98a8a6",
      "--c-focusRing": "#111111",
    },
  },
};
export const monsoon: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#244a3d",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#d5ded9",
      "--c-tone": "#bfcdc5",
      "--c-text": "#0a1a14",
      "--c-stroke": "#9aaea3",
      "--c-shadow": "#244a3d28",
      "--c-disabled": "#6a8078",
      "--c-mutedText": "#495651",
      "--c-disabledText": "#43514b",
      "--c-weekend": "#7c2d12",
      "--c-range": "#3c7e95",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#43514b",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#244a3d",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#0b1014",
      "--c-tone": "#151c22",
      "--c-text": "#eef4f2",
      "--c-stroke": "#26333a",
      "--c-shadow": "#244a3d28",
      "--c-disabled": "#334047",
      "--c-mutedText": "#91a19f",
      "--c-disabledText": "#98a8a6",
      "--c-weekend": "#ff7a7a",
      "--c-range": "#3c7e95",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#98a8a6",
      "--c-focusRing": "#ffffff",
    },
  },
};
export const nebula: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#681c9e",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#f5f3f7",
      "--c-tone": "#ebdff4",
      "--c-text": "#2b2533",
      "--c-stroke": "#ddd5e6",
      "--c-shadow": "#681c9e22",
      "--c-disabled": "#b0a0be",
      "--c-mutedText": "#67626d",
      "--c-disabledText": "#615c68",
      "--c-weekend": "#b91c1c",
      "--c-range": "#2196f3",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#615c68",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#b388ff",
      "--c-activeText": "#090812",
      "--c-backdrop": "#0b0a16",
      "--c-tone": "#18103a",
      "--c-text": "#ede7f6",
      "--c-stroke": "#3d2f70",
      "--c-shadow": "#b388ff28",
      "--c-disabled": "#3a2d60",
      "--c-mutedText": "#84808e",
      "--c-disabledText": "#8a8694",
      "--c-weekend": "#ff8a65",
      "--c-range": "#29b6f6",
      "--c-error": "#ff5252",
      "--c-outOfMonth": "#8a8694",
      "--c-focusRing": "#090812",
    },
  },
};
export const neon: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#80ec27",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f7f8f9",
      "--c-tone": "#e9f3eb",
      "--c-text": "#1f2937",
      "--c-stroke": "#bed3c3",
      "--c-shadow": "#80ec2722",
      "--c-disabled": "#8a9a88",
      "--c-mutedText": "#656c76",
      "--c-disabledText": "#5f6771",
      "--c-weekend": "#c62828",
      "--c-range": "#ff6b35",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#5f6771",
      "--c-focusRing": "#fcfcf5",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#76ff03",
      "--c-activeText": "#010401",
      "--c-backdrop": "#010401",
      "--c-tone": "#1a1f1a",
      "--c-text": "#00e676",
      "--c-stroke": "#1a4428",
      "--c-shadow": "#76ff0328",
      "--c-disabled": "#1a4020",
      "--c-mutedText": "#009b4f",
      "--c-disabledText": "#00a353",
      "--c-weekend": "#ff6d00",
      "--c-range": "#00bcd4",
      "--c-error": "#ff5252",
      "--c-outOfMonth": "#00a353",
      "--c-focusRing": "#020602",
    },
  },
};
export const noir: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#111111",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#ffffff",
      "--c-tone": "#f5f5f5",
      "--c-text": "#111111",
      "--c-stroke": "#e8e8e8",
      "--c-shadow": "#00000010",
      "--c-disabled": "#cccccc",
      "--c-mutedText": "#707070",
      "--c-disabledText": "#707070",
      "--c-weekend": "#111111",
      "--c-range": "#111111",
      "--c-error": "#cc0000",
      "--c-outOfMonth": "#707070",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#ffffff",
      "--c-activeText": "#111111",
      "--c-backdrop": "#111111",
      "--c-tone": "#1c1c1c",
      "--c-text": "#e8e8e8",
      "--c-stroke": "#2a2a2a",
      "--c-shadow": "#ffffff08",
      "--c-disabled": "#444444",
      "--c-mutedText": "#858585",
      "--c-disabledText": "#858585",
      "--c-weekend": "#e8e8e8",
      "--c-range": "#e8e8e8",
      "--c-error": "#ff4444",
      "--c-outOfMonth": "#858585",
      "--c-focusRing": "#111111",
    },
  },
};
export const pearl: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#3a2a42",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#ecebed",
      "--c-tone": "#dedce0",
      "--c-text": "#1f1624",
      "--c-stroke": "#c6c3ca",
      "--c-shadow": "#3a2a4226",
      "--c-disabled": "#9994a0",
      "--c-mutedText": "#645d67",
      "--c-disabledText": "#5e5862",
      "--c-weekend": "#9f3150",
      "--c-range": "#7b6d88",
      "--c-error": "#b91c1c",
      "--c-outOfMonth": "#5e5862",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#8a8a92",
      "--c-activeText": "#0e0e10",
      "--c-backdrop": "#141417",
      "--c-tone": "#1e1e22",
      "--c-text": "#e8e8ec",
      "--c-stroke": "#2a2a30",
      "--c-shadow": "#8a8a9220",
      "--c-disabled": "#4a4a52",
      "--c-mutedText": "#87878b",
      "--c-disabledText": "#8d8d91",
      "--c-weekend": "#ff6028",
      "--c-range": "#3a3a40",
      "--c-error": "#ff5252",
      "--c-outOfMonth": "#8d8d91",
      "--c-focusRing": "#0e0e10",
    },
  },
};
export const prism: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#0ea5e9",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f0f9ff",
      "--c-tone": "#e0f2fe",
      "--c-text": "#0c2340",
      "--c-stroke": "#bae6fd",
      "--c-shadow": "#0ea5e920",
      "--c-disabled": "#90c4d8",
      "--c-mutedText": "#5b6d82",
      "--c-disabledText": "#55677d",
      "--c-weekend": "#7c3aed",
      "--c-range": "#06b6d4",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#55677d",
      "--c-focusRing": "#0a1525",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#2563eb",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#061323",
      "--c-tone": "#0d1f3a",
      "--c-text": "#d8e8ff",
      "--c-stroke": "#173b72",
      "--c-shadow": "#2563eb2a",
      "--c-disabled": "#274260",
      "--c-mutedText": "#7b899d",
      "--c-disabledText": "#8190a4",
      "--c-weekend": "#ffb703",
      "--c-range": "#00c2a8",
      "--c-error": "#ff4d6d",
      "--c-outOfMonth": "#8190a4",
      "--c-focusRing": "#e6f0ff",
    },
  },
};
export const riso: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#2b3fe0",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#fef7e8",
      "--c-tone": "#fdebf3",
      "--c-text": "#1a1205",
      "--c-stroke": "#e5dcc8",
      "--c-shadow": "#2b3fe028",
      "--c-disabled": "#b8ab8c",
      "--c-mutedText": "#726a5d",
      "--c-disabledText": "#6c6557",
      "--c-weekend": "#be185d",
      "--c-range": "#2bce8b",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#6c6557",
      "--c-focusRing": "#fef7e8",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#4f63ff",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#17120b",
      "--c-tone": "#261827",
      "--c-text": "#f8ecd8",
      "--c-stroke": "#4a3829",
      "--c-shadow": "#4f63ff28",
      "--c-disabled": "#4b3b2c",
      "--c-mutedText": "#c8b99f",
      "--c-disabledText": "#c0b197",
      "--c-weekend": "#ff7ab8",
      "--c-range": "#2bce8b",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#c0b197",
      "--c-focusRing": "#fef7e8",
    },
  },
};
export const sandstone: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#c04e2f",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#f2e8e0",
      "--c-tone": "#fdddd0",
      "--c-text": "#6e4531",
      "--c-stroke": "#d4b0a0",
      "--c-shadow": "#c04e2f28",
      "--c-disabled": "#b08878",
      "--c-mutedText": "#805c49",
      "--c-disabledText": "#7c5643",
      "--c-weekend": "#8f2f1f",
      "--c-range": "#558b2f",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#7c5643",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#e3ae5c",
      "--c-activeText": "#111111",
      "--c-backdrop": "#1f1c18",
      "--c-tone": "#2f2b24",
      "--c-text": "#fdfbf7",
      "--c-stroke": "#5d5448",
      "--c-shadow": "#e3ae5c24",
      "--c-disabled": "#504840",
      "--c-mutedText": "#969490",
      "--c-disabledText": "#9d9b97",
      "--c-weekend": "#ff7a59",
      "--c-range": "#8bc34a",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#9d9b97",
      "--c-focusRing": "#1c1a17",
    },
  },
};
export const slate: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#475569",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#f1f5f9",
      "--c-tone": "#e2e8f0",
      "--c-text": "#0f172a",
      "--c-stroke": "#cbd5e1",
      "--c-shadow": "#47556920",
      "--c-disabled": "#94a3b8",
      "--c-mutedText": "#606674",
      "--c-disabledText": "#5a616f",
      "--c-weekend": "#c62828",
      "--c-range": "#0ea5e9",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#5a616f",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#3559e0",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#1a1e2b",
      "--c-tone": "#212638",
      "--c-text": "#ffffff",
      "--c-stroke": "#444b68",
      "--c-shadow": "#3559e02c",
      "--c-disabled": "#3a4060",
      "--c-mutedText": "#8d8f96",
      "--c-disabledText": "#94969c",
      "--c-weekend": "#ff6b6b",
      "--c-range": "#00bcd4",
      "--c-error": "#ef4444",
      "--c-outOfMonth": "#94969c",
      "--c-focusRing": "#141721",
    },
  },
};
export const snow: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#3a60d6",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#e2e5e9",
      "--c-tone": "#eceff4",
      "--c-text": "#212630",
      "--c-stroke": "#acb9cb",
      "--c-shadow": "#3a60d624",
      "--c-disabled": "#8898a8",
      "--c-mutedText": "#60656d",
      "--c-disabledText": "#5b5f68",
      "--c-weekend": "#b91c1c",
      "--c-range": "#26c6da",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#5b5f68",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#3a60d6",
      "--c-activeText": "#ffffff",
      "--c-backdrop": "#0b1014",
      "--c-tone": "#151c22",
      "--c-text": "#eef4f2",
      "--c-stroke": "#26333a",
      "--c-shadow": "#3a60d628",
      "--c-disabled": "#334047",
      "--c-mutedText": "#91a19f",
      "--c-disabledText": "#98a8a6",
      "--c-weekend": "#ff7a7a",
      "--c-range": "#26c6da",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#98a8a6",
      "--c-focusRing": "#ffffff",
    },
  },
};
export const solar: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#e67e22",
      "--c-activeText": "#111111",
      "--c-backdrop": "#fffbe8",
      "--c-tone": "#fff3c4",
      "--c-text": "#1e1a08",
      "--c-stroke": "#d4aa5a",
      "--c-shadow": "#e67e2224",
      "--c-disabled": "#b09060",
      "--c-mutedText": "#716d5b",
      "--c-disabledText": "#6c6855",
      "--c-weekend": "#9a3412",
      "--c-range": "#27ae60",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#6c6855",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#c89020",
      "--c-activeText": "#0e0b04",
      "--c-backdrop": "#0e0b04",
      "--c-tone": "#1e1808",
      "--c-text": "#f0d878",
      "--c-stroke": "#342a08",
      "--c-shadow": "#c8902028",
      "--c-disabled": "#2e2208",
      "--c-mutedText": "#928348",
      "--c-disabledText": "#99894b",
      "--c-weekend": "#ff8a50",
      "--c-range": "#558b2f",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#99894b",
      "--c-focusRing": "#fdf8e8",
    },
  },
};
export const split: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#e8c43d",
      "--c-activeText": "#111111",
      "--c-backdrop": "#fafaf6",
      "--c-tone": "#f2f0ea",
      "--c-text": "#1a1f2a",
      "--c-stroke": "#d4d0c4",
      "--c-shadow": "#e8c43d28",
      "--c-disabled": "#b5b0a4",
      "--c-mutedText": "#686c71",
      "--c-disabledText": "#63666c",
      "--c-weekend": "#1d4ed8",
      "--c-range": "#e83d9e",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#63666c",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#e8c43d",
      "--c-activeText": "#111111",
      "--c-backdrop": "#0b1014",
      "--c-tone": "#151c22",
      "--c-text": "#eef4f2",
      "--c-stroke": "#26333a",
      "--c-shadow": "#e8c43d28",
      "--c-disabled": "#334047",
      "--c-mutedText": "#91a19f",
      "--c-disabledText": "#98a8a6",
      "--c-weekend": "#ff7a7a",
      "--c-range": "#e83d9e",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#98a8a6",
      "--c-focusRing": "#111111",
    },
  },
};
export const temporal: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#27d1f4",
      "--c-activeText": "#111111",
      "--c-backdrop": "#f8fafc",
      "--c-tone": "#eef2f6",
      "--c-text": "#101820",
      "--c-stroke": "#ccd6df",
      "--c-shadow": "#27d1f422",
      "--c-disabled": "#95a2af",
      "--c-mutedText": "#5b6672",
      "--c-disabledText": "#56616d",
      "--c-weekend": "#b91c1c",
      "--c-range": "#fb923c",
      "--c-error": "#dc2626",
      "--c-outOfMonth": "#56616d",
      "--c-focusRing": "#111111",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#27d1f4",
      "--c-activeText": "#111111",
      "--c-backdrop": "#14252e",
      "--c-tone": "#242f52",
      "--c-text": "#f1f5f9",
      "--c-stroke": "#6366f1",
      "--c-shadow": "#27d1f42e",
      "--c-disabled": "#3a4870",
      "--c-mutedText": "#929ba2",
      "--c-disabledText": "#99a2a8",
      "--c-weekend": "#f472b6",
      "--c-range": "#fb923c",
      "--c-error": "#ef4444",
      "--c-outOfMonth": "#99a2a8",
      "--c-focusRing": "#122127",
    },
  },
};
export const velvet: ThemeFamily = {
  kind: "family",
  light: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#d64c7f",
      "--c-activeText": "#111111",
      "--c-backdrop": "#fef0f4",
      "--c-tone": "#fce4ed",
      "--c-text": "#2a1520",
      "--c-stroke": "#f0b8cc",
      "--c-shadow": "#d64c7f28",
      "--c-disabled": "#c09aaa",
      "--c-mutedText": "#75636b",
      "--c-disabledText": "#705d66",
      "--c-weekend": "#be123c",
      "--c-range": "#8e44ad",
      "--c-error": "#b91c1c",
      "--c-outOfMonth": "#705d66",
      "--c-focusRing": "#ffffff",
    },
  },
  dark: {
    [THEME_BRAND]: true,
    vars: {
      "--c-accent": "#ff4da6",
      "--c-activeText": "#120711",
      "--c-backdrop": "#120711",
      "--c-tone": "#261127",
      "--c-text": "#f9d8ea",
      "--c-stroke": "#4a2246",
      "--c-shadow": "#ff4da628",
      "--c-disabled": "#3b2339",
      "--c-mutedText": "#947d8b",
      "--c-disabledText": "#9b8391",
      "--c-weekend": "#ffc857",
      "--c-range": "#6ee7f9",
      "--c-error": "#ff6b6b",
      "--c-outOfMonth": "#9b8391",
      "--c-focusRing": "#fff0f8",
    },
  },
};

/** All built-in theme families, keyed by name. */
export const THEMES: Record<string, ThemeFamily> = {
  abyss,
  aurora,
  bauhaus,
  chalk,
  crimson,
  cyber,
  dracula,
  eclipse,
  espresso,
  fjord,
  graphite,
  industrial,
  meadow,
  mint,
  monsoon,
  nebula,
  neon,
  noir,
  pearl,
  prism,
  riso,
  sandstone,
  slate,
  snow,
  solar,
  split,
  temporal,
  velvet,
};
