// generated — do not edit manually, run: npm run build
import { CUSTOM_APPEARANCE_BRAND } from "../src/types/appearances";
import type { CustomAppearance } from "../src/types/appearances";

export const airy: CustomAppearance = { [CUSTOM_APPEARANCE_BRAND]: true, vars: { "--cal-radius": "0.4em", "--cal-container-radius": "0.6em", "--cal-border": "1px", "--cal-spacing": "1em", "--cal-shadow-sm": "none", "--cal-shadow-md": "none", "--cal-shadow-lg": "none", "--cal-font-size": "clamp(13px, 3.2cqw, 20px)", "--cal-text-xs": "0.68em", "--cal-text-sm": "0.78em", "--cal-text-md": "0.86em", "--cal-text-lg": "1em", "--cal-text-xl": "1.18em", "--cal-text-2xl": "1.35em", "--cal-text-day": "clamp(0.9em, 5.2cqi, 1.4em)", "--cal-weight-regular": "300", "--cal-weight-semibold": "300", "--cal-weight-bold": "400", "--cal-leading-tight": "1.1", "--cal-leading-normal": "1.6", "--cal-leading-relaxed": "2", "--cal-transition": "0.2s", "--cal-days-padding": "1.2em", "--cal-track-height": "4em", "--cal-day-ratio": "1 / 0.55", "--cal-popup-padding": "1em", "--cal-size-chip": "2em", "--cal-size-track-item": "5.5em", "--cal-opacity-disabled": "0.3", "--cal-opacity-muted": "0.4", "--cal-opacity-hover": "0.75", "--cal-letter-spacing": "0.1em" } };
export const bubble: CustomAppearance = { [CUSTOM_APPEARANCE_BRAND]: true, vars: { "--cal-radius": "1.5em", "--cal-container-radius": "2.2em", "--header-min-height": "4em", "--cal-border": "1px", "--cal-spacing": "0.7em", "--cal-shadow-sm": "0 0.15em 0.5em var(--c-x)", "--cal-shadow-md": "0 0.25em 0.9em var(--c-x)", "--cal-shadow-lg": "0 0.35em 1.4em var(--c-x)", "--cal-font-size": "clamp(12px, 2.9cqw, 19px)", "--cal-text-sm": "0.82em", "--cal-text-md": "0.88em", "--cal-text-lg": "1em", "--cal-text-xl": "1.08em", "--cal-text-2xl": "1.14em", "--cal-text-day": "clamp(0.78em, 4.6cqi, 1.22em)", "--cal-leading-normal": "1.35", "--cal-transition": "0.28s", "--cal-days-padding": "1em", "--cal-track-height": "4.5em", "--cal-day-ratio": "1 / 1", "--cal-popup-padding": "0.9em", "--cal-size-chip": "2.4em", "--cal-size-track-item": "4.5em", "--cal-opacity-disabled": "0.45", "--cal-opacity-muted": "0.65", "--cal-opacity-hover": "0.82" } };
export const compact: CustomAppearance = { [CUSTOM_APPEARANCE_BRAND]: true, vars: { "--cal-radius": "0.3em", "--cal-border": "1px", "--cal-spacing": "0.35em", "--cal-shadow-sm": "0 0.05em 0.15em var(--c-x)", "--cal-shadow-md": "0 0.1em 0.3em var(--c-x)", "--cal-shadow-lg": "0 0.1em 0.4em var(--c-x)", "--cal-font-size": "clamp(11px, 2.3cqw, 15px)", "--cal-text-2xs": "0.58em", "--cal-text-xs": "0.68em", "--cal-text-sm": "0.76em", "--cal-text-md": "0.82em", "--cal-text-lg": "0.9em", "--cal-text-xl": "1em", "--cal-text-2xl": "1.04em", "--cal-text-day": "clamp(0.68em, 4.2cqi, 1em)", "--cal-leading-tight": "1.05", "--cal-leading-normal": "1.2", "--cal-transition": "0.15s", "--cal-days-padding": "0.45em", "--cal-track-height": "3.2em", "--cal-day-ratio": "1 / 0.7", "--cal-popup-padding": "0.5em", "--cal-size-chip": "1.9em", "--cal-size-track-item": "3em", "--cal-opacity-disabled": "0.4", "--cal-opacity-muted": "0.55", "--cal-opacity-hover": "0.75" } };
export const loft: CustomAppearance = { [CUSTOM_APPEARANCE_BRAND]: true, vars: { "--cal-radius": "1em", "--cal-container-radius": "2.5em", "--header-min-height": "5em", "--cal-border": "0px", "--cal-spacing": "1em", "--cal-shadow-sm": "0 0.3em 0.9em var(--c-x)", "--cal-shadow-md": "0 0.8em 2em var(--c-x)", "--cal-shadow-lg": "0 1.5em 3.5em var(--c-x)", "--cal-font-size": "clamp(14px, 3.5cqw, 22px)", "--cal-text-xs": "0.75em", "--cal-text-sm": "0.84em", "--cal-text-md": "0.9em", "--cal-text-lg": "1em", "--cal-text-xl": "1.12em", "--cal-text-2xl": "1.2em", "--cal-text-day": "clamp(0.82em, 4.8cqi, 1.28em)", "--cal-weight-semibold": "500", "--cal-weight-bold": "600", "--cal-leading-normal": "1.4", "--cal-leading-relaxed": "1.7", "--cal-transition": "0.35s", "--cal-days-padding": "1.8em", "--cal-track-height": "5em", "--cal-day-ratio": "1 / 1", "--cal-popup-padding": "1em", "--cal-size-chip": "2.5em", "--cal-size-track-item": "5em", "--cal-opacity-disabled": "0.35", "--cal-opacity-muted": "0.6", "--cal-opacity-hover": "0.82" } };
export const soft: CustomAppearance = { [CUSTOM_APPEARANCE_BRAND]: true, vars: { "--cal-radius": "0.75em", "--cal-border": "1px", "--cal-spacing": "0.7em", "--cal-shadow-sm": "0 0.15em 0.5em var(--c-x)", "--cal-shadow-md": "0 0.25em 0.8em var(--c-x)", "--cal-shadow-lg": "0 0.3em 1.2em var(--c-x)", "--cal-text-lg": "0.96em", "--cal-text-xl": "1.06em", "--cal-text-day": "clamp(0.74em, 4.4cqi, 1.16em)", "--cal-leading-normal": "1.35", "--cal-transition": "0.25s", "--cal-days-padding": "0.95em", "--cal-popup-padding": "0.85em", "--cal-size-chip": "2.2em", "--cal-size-track-item": "4.2em", "--cal-opacity-disabled": "0.45", "--cal-opacity-muted": "0.65", "--cal-opacity-hover": "0.82" } };
export const square: CustomAppearance = { [CUSTOM_APPEARANCE_BRAND]: true, vars: { "--cal-radius": "0", "--cal-border": "1px", "--cal-spacing": "0.5em", "--cal-text-sm": "0.78em", "--cal-text-md": "0.84em", "--cal-text-lg": "0.94em", "--cal-text-day": "clamp(0.72em, 4.4cqi, 1.12em)", "--cal-leading-tight": "1", "--cal-leading-normal": "1.2", "--cal-transition": "0.12s", "--cal-day-ratio": "1 / 1", "--cal-popup-padding": "0.7em", "--cal-size-chip": "2em", "--cal-size-track-item": "3.8em", "--cal-opacity-disabled": "0.3", "--cal-opacity-muted": "0.5", "--cal-opacity-hover": "0.72", "--cal-letter-spacing": "0.04em" } };
