name: Chromatic

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

jobs:
  chromatic:
    if: github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Publish to Chromatic
        uses: chromaui/action@84e0c70520cf012d7cbcd0d9677b4240f893e25e # latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true
